[package]
name = "argster-example"
version = "0.1.0"
edition = "2021"
description = "A test crate for argster"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argster = { path = "../argster" }
